plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.3.0'
    id 'maven-publish'
}

repositories {
    mavenLocal()
    mavenCentral()
}

group = 'dshackle'

dependencies {
    implementation 'org.yaml:snakeyaml:1.24'
    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_24
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_24
    targetCompatibility = JavaVersion.VERSION_24
}

test {
    useJUnitPlatform()
}
version '1.0.0'

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        mavenLocal()
    }
}
